# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kurt Stubbings Portfolio
email: kurtstubbings@gmail.com
description: > # this means to ignore newlines until "baseurl:"
#page description - write something better
  This is the portfolio site for Kurt Stubbings,
  a digital designer and developer from Aylesbury.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kurtstubbings.com" # the base hostname & protocol for your site
twitter_username: kuuurttyy
github_username:  kuuurttyy

# Build settings
markdown: kramdown
